image: node:11
pipelines:
  branches:
    develop:
      - step:
        name: build application for staging
        caches:
        - node
        script:
        - yarn install
        - yarn make
        artifacts:
        - dist/kiosk-client-*-mac.zip
        - dist/kiosk-client Setup *.exe
