image: acodeninja/electron-builder:latest
definitions:

  build-assets: &build-assets
    name: build assets
    caches:
      - node
    script:
      - yarn install
      - yarn asset:build
    artifacts:
      - static/assets/**

pipelines:
  default:
    - step: *build-assets

  branches:
    develop:
      - step: *build-assets
      - step:
          name: staging build
          caches:
            - node
          script:
            - yarn install
            - yarn dist:all:staging
          artifacts:
            - dist/*.zip
