image: acodeninja/electron-builder:latest
definitions:

  build-assets: &build-assets
    name: build assets
    caches:
      - node
    script:
      - yarn install
      - yarn compile
    artifacts:
      - static/assets/**
      - dist/**

  staging-build-mac: &staging-build-mac
    name: staging build (mac)
    caches:
      - node
    script:
      - yarn install
      - yarn dist:staging:mac
    artifacts:
      - dist/*.zip

  staging-build-linux: &staging-build-linux
    name: staging build (linux)
    caches:
      - node
    script:
      - yarn install
      - yarn dist:staging:linux
    artifacts:
      - dist/*.zip

  staging-build-win: &staging-build-win
    name: staging build (win)
    caches:
      - node
    script:
      - yarn install
      - yarn dist:staging:win
    artifacts:
      - dist/*.zip

pipelines:
  default:
    - step: *build-assets

  branches:
    develop:
      - step: *build-assets
      - parallel:
          - step: *staging-build-mac
          - step: *staging-build-linux
          - step: *staging-build-win
      - step:
          name: deploy builds
          deployment: staging
          image: atlassian/pipelines-awscli
          script:
            - aws s3 cp dist/ s3://$S3_BUCKET/ --recursive --exclude "*" --include "*.zip"
