image: node:10.12
pipelines:
  default:
  - step:
      name: build application
      caches:
      - node
      script:
      - apt-get update && apt-get install -yq fakeroot
      - yarn install
      - yarn make
      artifacts:
        - out/make/*.zip
