image: acodeninja/electron-builder:latest
pipelines:
  branches:
    develop:
      - step:
          name: build application for staging
          caches:
          - node
          script:
          - yarn install
          - yarn dist:all:staging
          artifacts:
          - dist/*.zip
