image: node:11
pipelines:
  branches:
    develop:
      - step:
          name: build application for staging
          caches:
          - node
          script:
          - dpkg --add-architecture i386
          - wget -nc https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Ubuntu_18.10_standard/Release.key
          - apt-key add Release.key
          - echo 'deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Ubuntu_18.10_standard ./' >> /etc/apt/sources.list
          - apt-get update
          - apt-get install --no-install-recommends -y libopenjp2-tools winehq-stable
          - yarn install
          - yarn dist:all:staging
          artifacts:
          - dist/kiosk-client-*-mac.zip
          - dist/kiosk-client Setup *.exe

